site_name: BOJ Java Notes
theme:
  name: material
  language: ko
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: slate
      primary: blue
      accent: indigo

nav:
  - 소개: index.md
  - 학습 계획: study-plan.md
  - 템플릿:
      - Java 입출력 템플릿: templates/java-io-template.md
  - 알고리즘:
      - 시간 복잡도: algorithms/time-complexity.md
      - 이분 탐색: algorithms/binary-search.md
      - DFS/BFS: algorithms/bfs-dfs.md
  - 문제 메모:
      - BOJ 1920: problems/01920.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite
  - pymdownx.details
  - pymdownx.superfences